ignore:
  - "**/databinding/**/*.*"
  - "**/android/databinding/*Binding.*"
  - "**/BR.*"
  - "**/R.*"
  - "**/R$*.*"
  - "**/BuildConfig.*"
  - "**/Manifest*.*"
  - "**/*_MembersInjector.*"
  - "**/Dagger*Component.*"
  - "**/Dagger*Component$Builder.*"
  - "**/*Module_*Factory.*"
  - "**/*Fragment*.*"
  - "**/*Activity*.*"
  - "**/*Adapter*.*"
  - "**/*ViewPager*.*"
  - "**/*ViewHolder*.*"
  - "**/*Module*.*"
  - "**/*Database*.*"
  - "**/Database*.*"
  - "**/*Provider*.*"
  - "**/*Notification*.*"
  - "**/*android*"
  - "**/android/**"
  - "**/NoteUploader.java"
  - "**/NoteBackup.java"
